### PR TITLE
rework around ir-ctrl

### PR DESCRIPTION
**Pull request by curcuz**

### CODE REVIEW

**Comment by anujdeshpande** [comment]
Looks neat! Going to set this up again over the weekend and give it a run

**Comment by curcuz** [comment]
@anujdeshpande did you have a chance to test it? looking fwd to merging this and get HHR involved for GUI and project streamlining :)

**Comment by anujdeshpande** [comment]
```
anujdeshpande@BaeBlade:~/balena/balena-ir-remote$ curl --request POST http://192.168.86.27/v1/ir --data '{"name":"ac"}' --header "Content-Type: application/json"
^C
anujdeshpande@BaeBlade:~/balena/balena-ir-remote$
```
My curl command just hangs till I close it

**Comment by anujdeshpande** [comment]
I’m using a shield from an old project I was involved with. Wired below - 

image 

It’s got a TSOP IR receiver and regular IR LEDs

**Comment by anujdeshpande** [comment]
@curcuz I edited my comment a couple of times as I was debugging. Had some curl woes- sorry about that.

How should I enable additional debug log? How does your hardware setup look like

**Comment by anujdeshpande** [comment]
Did some more debugging

```
bash-5.0# ir-ctl --device=/dev/lirc1 -r
^C
bash-5.0# ir-ctl --device=/dev/lirc0 -r
/dev/lirc0: device cannot receive raw ir
bash-5.0# 
```

I see 2 devices, and only one of them can receive. Tried with a couple of remotes, but no joy on the cli. Will debug more.

**Comment by curcuz** [comment]
@anujdeshpande I'm using this hw combo https://www.amazon.co.uk/ILS-Infrared-Transmitter-Receiver-Arduino/dp/B07912FFXV/

maybe your hardware is being enumerated in the opposite order, can you please try swapping lirc0/lirc1 in your test?

**Pull request merged**
